---

- name: Install Qpid CCP Server package
  yum:
    name: qpid-cpp-server

- name: Install storage package
  yum:
    name: "{{ qpid_cpp_server_storage_pkg }}"

- name: Configure Qpid daemon
  template:
    src: qpidd.conf.j2
    dest: "{{ qpid_cpp_server_daemon_config_file }}"
  notify:
    - Restart Qpid daemon

- name: Make qpidd service running
  service:
    name: qpidd
    enabled: yes
    state: running
