---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat"

- name: Add EPEL YUM repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: "{{ qpid_cpp_server_epel_yumrepo_url }}"
    gpgkey: "{{ qpid_cpp_server_epel_yumrepo_gpgkey }}"
    params: "{{ qpid_cpp_server_epel_yumrepo_params }}"
  when: qpid_cpp_server_epel_install
  tags:
    - qpid_cpp_server_pkg

- name: Add Qpid YUM repo
  yum_repository:
    name: qpid
    description: Qpid YUM repo
    baseurl: "{{ qpid_cpp_server_qpid_yumrepo_url }}"
    gpgcheck: no
    params: "{{ qpid_cpp_server_qpid_yumrepo_params }}"
  when: ansible_distribution_major_version | int == 6
  tags:
    - qpid_cpp_server_pkg

- name: Install Qpid CCP Server package
  package:
    name: "{{ qpid_cpp_server_pkg }}"
  notify:
    - Restart Qpid daemon
  tags:
    - qpid_cpp_server_pkg

- name: Install Qpid storage package
  package:
    name: "{{ qpid_cpp_server_storage_pkg }}"
  notify:
    - Restart Qpid daemon
  tags:
    - qpid_cpp_server_pkg

- name: Configure Qpid daemon
  template:
    src: qpidd.conf.j2
    dest: "{{ qpid_cpp_server_daemon_config_file }}"
  notify:
    - Restart Qpid daemon
  tags:
    - qpid_cpp_server_config

- name: Enable qpidd service
  service:
    name: qpidd
    enabled: yes
  tags:
    - qpid_cpp_server_service

- name: Run qpidd service
  service:
    name: qpidd
    state: running
  register: qpid_cpp_server_service_started
  tags:
    - qpid_cpp_server_service
